helm_repository: &helm_repo 'http://sonatype-nexus-service.nexus-nexus.svc.cluster.local:8081/repository/purplesky-charts/'
##############
# Argo Apps declaration
#############
applications:
  sb-app:
    name: sb-app
    enabled: true
    source: *helm_repo
    chart_name: sb-app
    destination: sb-staging
    source_ref: 0.1.0 # helm chart version
    values:
      fullnameOverride: sb-app
      image:
        repository: quay.io/spring-boot-helm-openshift-argocd
        tag: 1.3 # new image version
      config:
        favourite:
          cheese: Staging Cheddar
    project: sb-app-suite
