helm_repository: &helm_repo 'https://nexus-nexus.apps.cluster-thxb7.thxb7.sandbox393.opentlc.com/repository/helm-charts/'
# image_version: 1.3
##############
# Argo Apps declaration
#############
applications:
  sb-app:
    name: sb-app-staging
    enabled: true
    source: *helm_repo
    chart_name: sb-app
    destination: sb-staging
    source_ref: 0.1.1 # helm chart version
    values:
      fullnameOverride: sb-app-staging
      image_repository: quay.io/swinches
      image_name: spring-boot-helm-openshift-argocd
      image_version: 1.3 # new image version      
      image:
        repository: quay.io/swinches/spring-boot-helm-openshift-argocd
        tag: 1.3 # new image version
      config:
        favourite:
          cheese: Staging Smelly Gorgonzola
    project: sb-app-suite
