{{- if .Values.applications }}
{{- range $app := .Values.applications }}
{{- if $app.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: {{ .name }}
  labels:
{{- if .values.image_version }}
    image_version: {{ .values.image_version }}
{{- end}}
{{- if .values }}
{{- if .values.fullnameOverride }}
{{- if contains .values.fullnameOverride .name }}
    app.kubernetes.io/instance: {{ .values.fullnameOverride }}
{{- end }}
{{- else -}}
    app.kubernetes.io/instance: {{ .name }}
{{- end }}
{{- end }}
spec:
  destination:
    namespace: {{ .destination | default "sb-ci-cd" }}
    server: {{ .cluster_api | default "https://kubernetes.default.svc" }}
{{- if .project }}
  project: {{ .project }}
{{- else -}}
  project: default
{{- end }}
  source:
{{- if not .no_helm }}
    helm:
      releaseName: {{ .name }} # TODO change to env
{{- if .helm_values }}
      valueFiles:
{{- toYaml .helm_values | nindent 8 }}
{{- end }}
{{- if .values }}
      values: |
{{- toYaml .values | nindent 8 }}
{{- end }}
{{- end }}
    {{- if .source_path }}
    path: {{ .source_path }}
    {{- end }}
    repoURL: {{ .source }}
    targetRevision: {{ .source_ref | default "master" | quote }}
    {{- if .chart_name }}
    chart: {{ .chart_name }}
    {{- end}}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      validate: true
  ignoreDifferences:
    - group: apps.openshift.io
      kind: DeploymentConfig
      jsonPointers:
        - /spec/replicas
        - /spec/template/spec/containers/0/image
        - /spec/triggers/0/imageChangeParams/lastTriggeredImage
        - /spec/triggers/1/imageChangeParams/lastTriggeredImage
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
        - /spec/template/spec/containers/0/image
        - /spec/template/spec/containers/1/image
{{- end }}
{{- end }}
{{- end }}
